# Generated by Django 4.0.5 on 2022-06-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_alter_transactions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('complete', 'complete'), ('failed', 'failed')], max_length=50),
        ),
    ]
